### ISSUE TITLE
Pub/sub message for each step

### ISSUE THREAD

**Issue by tlbdk** [GoogleCloudPlatform/cloud-builders#124]
Use case could be to update github commit status on each step like circle ci does for their builds.

**Comment by bendory** [comment]
Interesting idea; will forward to our Product Manager for consideration / prioritization...

**Comment by svachmic** [comment]
I am currently researching if it's possible to integrate Cloud Builder into GitHub PR workflow. I know GitHub has integrations with Travis, Circle, CodeShip etc. which are incredibly helpful because I don't have to go to a separate website to check the status of my build.

Is there any workaround/trick how to do this, or we are currently left with a "feature request"?

**Comment by tlbdk** [comment]
I have a project trying to build that here, that I'm planning to have a look at again when the day job stops getting in the way: https://github.com/connectedcars/buildstatus

As for the build steps you could read the build log and regex what step is running.

**Comment by nandosangenetto** [comment]
It would be awesome. 

I'm trying to do that as well.

**Comment by nandosangenetto** [comment]
Actually, I'm using Cloud Functions as bridge between Container Builder and GitHub.

What do you think about that approach?

**Comment by bendory** [comment]
We indeed have many users who choose GCF as a bridge between GCB and other (Google and non-Google) services. This is a working solution while we build in better first-class support.

**Comment by bendory** [comment]
closing this issue as off-topic

For support or to file feature requests with the hosted Google Cloud Build service, please use Google Cloud Support.
