### ISSUE TITLE
go: selecting the version of Go to build with?

### ISSUE THREAD

**Issue by evanj** [GoogleCloudPlatform/cloud-builders#19]
It would be great if there was some way to specify the Go release to use to build a container. As far as I can tell, this is not controllable. This is not a critical issue for us at the moment, but at some point we will want to control when we upgrade between major releases. I don't have a good idea for how this should work, although maybe having a `GO_VERSION` variable would work, although you would then need to ship all the versions in your base image. Alternatively, maybe you need to replicate *all* the tags from the upstream `golang` Docker image?

**Comment by bendory** [comment]
Thank you for the feedback. In the coming week, we'll look to clarify the versions available like we've done with the [Docker builder](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/docker); you'll likely specify your desired version via tag rather than an envvar.

Does that sound like it will meet your needs?

**Comment by evanj** [comment]
Yes, definitely: Having the uptsream `golang` image tags available would definitely work. Thanks!

**Comment by abhigenie92** [comment]
But you can use version number, any reason for that?

**Comment by bendory** [comment]
closing as obsolete; see https://github.com/GoogleCloudPlatform/cloud-builders/issues/677

note that `golang` lets you specify version by tag
