### ISSUE TITLE
git removed from yarn cloud builder 

### ISSUE THREAD

**Issue by Jakedavies** [GoogleCloudPlatform/cloud-builders#195]
in commit https://github.com/GoogleCloudPlatform/cloud-builders/commit/2d9d102aeb9d286663d337b1394ce31e1ff04bc3 git was removed from the could builder, which seems to have broken yarn. My yarn is now getting the following error when attempting install

```
Starting Step #0
Step #0: Already have image (with digest): gcr.io/cloud-builders/yarn
Step #0: yarn install v1.3.2
Step #0: [1/4] Resolving packages...
Step #0: [2/4] Fetching packages...
Step #0: error Couldn't find the binary git
Step #0: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Finished Step #0
```

**Comment by ImJasonH** [comment]
Sorry about that! Thanks for reaching out. I have no problem including Git in this image, but I'm a bit surprised since [the installation instructions](https://yarnpkg.com/en/docs/install#linux-tab) don't make any mention of a requirement that Git is installed. I simply copied the instructions from that page.

I'll send a PR to install Git again, which should be released soon. Sorry for the breakage!
