### ISSUE TITLE
fatal: could not read Username for 'https://github.com'

### ISSUE THREAD

**Issue by anr** [GoogleCloudPlatform/cloud-builders#328]
I'm using this test config:

```yaml
steps:
  - name: gcr.io/cloud-builders/go
    args: ['get', './...']
    env: ['PROJECT_ROOT=${REPO_NAME}']
```

which works locally with

```bash
cloud-build-local --dryrun=false --substitutions REPO_NAME=github.com/anr/moai .
```

but fails in GCB, when the build is triggered by a git push, with:

```
starting build "aca8a515-39c6-4035-9e68-eeb765f0d382"

FETCHSOURCE
Initialized empty Git repository in /workspace/.git/
From https://source.developers.google.com/p/moai-x/r/github-anr-moai
* branch b76c7e165d9aa59a7789fa5fe222cb6a9614e687 -> FETCH_HEAD
HEAD is now at b76c7e1 Another test
BUILD
Already have image (with digest): gcr.io/cloud-builders/go
Creating shadow workspace and symlinking source into "./gopath/src/github-anr-moai".
Documentation at https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/go/README.md
Running: go get ./...
# cd .; git clone https://github.com/anr/moai /workspace/gopath/src/github.com/anr/moai
Cloning into '/workspace/gopath/src/github.com/anr/moai'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/anr/moai/config: exit status 128
package github.com/anr/moai/proto: cannot find package "github.com/anr/moai/proto" in any of:
/usr/local/go/src/github.com/anr/moai/proto (from $GOROOT)
...
ERROR
ERROR: build step 0 "gcr.io/cloud-builders/go" failed: exit status 1
```

Looks like a Github integration problem, but I think this step was working the day before yesterday.

Thanks

**Comment by anr** [comment]
Thanks, it is indeed a private repo. I'll go through the instructions.

Funny that it seemed to work before:

```
starting build "d9fe9bd9-2dcd-45d8-b2a4-f1c111e46037"

FETCHSOURCE
Initialized empty Git repository in /workspace/.git/
From https://source.developers.google.com/p/moai-x/r/github-anr-moai
* branch 7fc3592f076086898234fc8db9f4707be340fabc -> FETCH_HEAD
HEAD is now at 7fc3592 Add cloud build
BUILD
Starting Step #0

...

Starting Step #2
Step #2: Already have image (with digest): gcr.io/cloud-builders/go
Step #2: Creating shadow workspace and symlinking source into "./gopath/src/github.com/anr/moai".
Step #2: Documentation at https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/go/README.md
Step #2: Running: go get ./...
Finished Step #2
```

**Comment by ImJasonH** [comment]
I don't think I have enough information to say why it worked before.

It looks like the repo you're building is mirrored from `github.com/anr/moai` (which is private), so it might be that when it worked, you didn't have any imports from `github.com/anr/moai/some/subpackage`, in which case the repo didn't need to `go get` anything from there. By adding an import of `some/subpackage`, `go get` decides it needs to clone that repo, and can't because it's private.

This is definitely an area where the mirror makes things more confusing, since we don't (and shouldn't!) rewrite Go imports to point to the mirrored repo accessible to the builder service account.

/cc @wlynch who has thought about better ways of handling submodules, which seems similar to this issue.

I'm going to close this issue for now since it sounds like the private GitHub docs should work for you. Feel free to reopen if they don't.
