### ISSUE TITLE
Running golint or other go installed tools is clumsy

### ISSUE THREAD

**Issue by byates-va** [GoogleCloudPlatform/cloud-builders#34]
Hey all,

Would you be willing to allow overriding of the command run at the end of the wrapper script for the go container, for example to run golint instead of go?

I would also be in support of a golint specfic image, since golint is a pretty popular tool as far as I know.

I have used workarounds such as building my own wrapper script for my own container, as well as using go run and running golint from source from within your go conatiner, but neither of those are ideal.

**Comment by skelterjohn** [comment]
Thanks for the feedback. I feel like your use-case is an important one and I think we can work something out.

Have you tried using gcr.io/cloud-builders/go as a base image, and making a wrapper script that calls the provided prepare_workspace function? (not sure if that's the process you used when you said you tried your own wrapper script)

If a modification directly on the go builder, how were you thinking it'd be specified? An "easy" solution would be to give it an env var 'TOOL=golint' or some-such, but I'm not a fan of using env vars like that. We can't use entrypoint, because that would forget about the wrapper.

How many similar tools do you think would be appropriate that make use of the go workspace conventions? So far it's the go tool, the golang-project binary, glide, and now golint. Maybe it makes the most sense to add a gcr.io/cloud-builders/golint builder, using the wrapper script + prepare_workspace method I outlined above.

**Comment by byates-va** [comment]
@skelterjohn would it possibly be as simple as using `"$@"` instead of `go "$@"`? I feel like it wouldn't... because that's a breaking change for one, and two I know you don't want to force the user to be putting the tool to execute in the arg list every time...

Your right in that you can't quite do what is documented here https://cloud.google.com/container-builder/docs/api/custom-build-steps#entrypoint because you need your wrapper script to be the entrypoint. And you also can't really be smart about the first arg being the entrypoint either, because how do you know if that's a tool or not. 

I did not think to call your prepare workspace function, but also my own fully custom wrapper script only needed to be I think 4 lines total since I don't have to account for all the different ways the workspace could be configured...

**Comment by byates-va** [comment]
When I first used container builder, I wondered why we wouldn't be allowed to define our own location for the volume mount of `/workspace`. If we were able to do that, there would be no need for the wrapper script or this image... I would be able to do everything I need using the raw golang 1.8 image. I'll take that feedback and discussion directly to the container builder team through our google customer engineering channels.

**Comment by skelterjohn** [comment]
This feedback is directly to the container builder team :) I'm one of the
senior engineers on it.

**Comment by byates-va** [comment]
Maybe this is kind of a moot point for the golint case... as I did some more work around this only to find out that golint doesn't return a non zero exit code on linting failures, and digging into why they seem pretty adamant that golint shouldn't be run in CI (they mention this in both their readme and several issues around this).

Feel free to close this issue @skelterjohn and see if this or any other go tool issues come up again...

**Comment by nhooyr** [comment]
Would be cool to run `gometalinter` as well.

**Comment by k1ng440** [comment]
yes it would be cool

**Comment by k1ng440** [comment]
I found this document which is pretty useful. 
https://medium.com/@lestrrat/taming-google-container-builder-22a6dded155c

**Comment by bendory** [comment]
closing as obsolete; see also https://github.com/GoogleCloudPlatform/cloud-builders/issues/677
