### ISSUE TITLE
include cmake in cloud-builders/bazel image

### ISSUE THREAD

**Issue by bbarnes52** [GoogleCloudPlatform/cloud-builders#373]
this is required when using [rules_foreign_cc](https://github.com/bazelbuild/rules_foreign_cc) @irengrig

**Comment by mancini0** [comment]
You can use rules_foreign_cc's rules_foreign_cc_dependencies() function to specify that you want to use cmake built from sources:

In your WORKSPACE:

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")
rules_foreign_cc_dependencies(["//:built_cmake_toolchain"])

In BUILD
load("@rules_foreign_cc//for_workspace:cmake_build.bzl", "cmake_tool")
toolchain(
    name = "built_cmake_toolchain",
    toolchain = "@rules_foreign_cc//tools/build_defs/native_tools:built_cmake",
    toolchain_type = "@rules_foreign_cc//tools/build_defs:cmake_toolchain",
)


Note this will allow you to use cmake, but your build will still fail because Make itself  will not be 
found, even though the gnu toolchain is detected in the image - I created this issue to address that problem.

**Comment by bendory** [comment]
closing as obsolete, reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/667
