### ISSUE TITLE
Bazel - kubectl is missing

### ISSUE THREAD

**Issue by christian-roggia** [GoogleCloudPlatform/cloud-builders#381]
Currently, it is impossible to use Bazel for deployment on GKE or other Kubernetes clouds. The kubectl is missing in the image and the rules_k8s require kubectl to be installed and already authenticated on the machine.

Deployment on Kubernetes is a fundamental feature for completing the Continuous Deployment cycle and being forced to use the [cloud-builders/kubectl](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/kubectl) image instead of the functionalities already provided from Bazel's rules_k8s is not a good option.

The Bazel image should already include a pre-configured kubectl. As an alternative, a secondary cloud builder image called "bazel-k8s" or "bazel-kubectl" should be provided.

This workaround is potentially temporary as described in the issue https://github.com/bazelbuild/rules_k8s/issues/21 but it is necessary for the current status of Bazel.

**Comment by nlopezgi** [comment]
Hi @christian-roggia ,
rules_k8s owner here. rules_k8s (no longer)  needs kubectl to be pre-installed. We now support both pulling a pre-existing binary and building kubectl from source. Details are here: https://github.com/bazelbuild/rules_k8s/tree/master/toolchains/kubectl

Please let me know if this will work for your use case, otherwise we can help you get your use case supported (commented on referenced issue that I had forgotten to update).

**Comment by christian-roggia** [comment]
It looks like this a working solution, therefore, I will close this issue.
