### ISSUE TITLE
Specify machine_type on a per-step basis 

### ISSUE THREAD

**Issue by emarx** [GoogleCloudPlatform/cloud-builders#461]
I would love if there were a way to specify a machine type on a per-step basis. We have a large scala project to compile, which requires using a N1_HIGHCPU_32 machine, and 20 or so docker containers to push up after the project is compiled. With the machine type defined at the level of the full workflow, I have to use a N1_HIGHCPU_32 node to push docker containers, and because these don't seem to be allocated freely, the steps queue up, making an otherwise speedy build rather slow. 

Not sure where to post this request -- please let me know if it is more useful somewhere else.

**Comment by rafikk** [comment]
Hi @emarx, thanks for your feature request!

I think this question is due to a misunderstanding, but please let me know if I'm mistaken:

All steps of a build run on the same machine. In regards to queueing: your entire build can be queued if there isn't a machine available when it's requested (usually the case for high CPU machines since we don't pool those), but individual steps are _not_ queued; they are executed serially on the same machine. If you have steps that can run concurrently, you can use the `waitFor` option to have those steps execute concurrently.

If there's documentation that can be improved on this point, please let me know.

(If instead you're asking for the ability to distribute steps onto separate machines, that's a very different issue. Please clarify if that's the case.)

**Comment by emarx** [comment]
Ah, thank you for your super fast response, @rafikk! I indeed had that misunderstanding. Thank you for clarifying.

As a recommendation on documentation, this section https://cloud.google.com/cloud-build/docs/build-config#build_steps could read


> Build steps
> A build step specifies an action that you want Cloud Build to perform. For each build step, Cloud Build executes a docker container as an instance of docker run. Build steps are analogous to commands in a script and provide you with the flexibility of executing arbitrary instructions in your build. If you can package a build tool into a container, Cloud Build can execute it as part of your build. *Build steps are all run on a single machine.*

**Comment by rafikk** [comment]
No problem. Thanks for the suggestion! Will have someone from the Docs team take a look.

Hope GCB is working well for you!
