### ISSUE TITLE
kubectl does not support export then apply ?

### ISSUE THREAD

**Issue by mbriot** [GoogleCloudPlatform/cloud-builders#495]
The next command work fine in my cluster : 
` kubectl get cm api-constants --namespace=default --export -o yaml | kubectl apply --namespace=preprod -f -`

But does not work in cloud build with kubectl cloud-builders.

<img width="748" alt="Capture d’écran 2019-05-21 à 18 06 46" src="https://user-images.githubusercontent.com/5500454/58112172-42d47500-7bf3-11e9-9be3-0c91aaeb8db5.png">

**Comment by LanceSandino** [comment]
This is because the `kubectl.bash` (The entry point of the builder) echos the command before the command is executed. 

So you can either modify the file to not do that, or what I do is just add `grep -v “Running”` to my pipe

(Might need to bash out) 

*so:*

`get cm api-constants --namespace=default --export -o yaml | grep -v “Running” | kubectl apply --namespace=preprod -f -`

*or bash out:*

```
entrypoint: ‘bash’
args:
  - ‘-c’
  - |
     kubectl.bash get cm api-constants --namespace=default --export -o yaml | grep -v “Running” | kubectl apply --namespace=preprod -f -
```

**Comment by bendory** [comment]
closing as obsolete; reference https://github.com/GoogleCloudPlatform/cloud-builders/issues/638
