### ISSUE TITLE
Best place to file build trigger + source repo bugs?

### ISSUE THREAD

**Issue by ofpiyush** [GoogleCloudPlatform/cloud-builders#66]
I have set up build triggers from my github repos.

Some pushes just fail to show up. 

I have to make another fake push on github for the sync to trigger into source code repository and trigger the build.

While you guys fix the bug, a way to say "Sync now" on a repo will help me keep my workflow going on.

**Comment by bendory** [comment]
Hi ofpiyush, thank you for the bug report. Globally, build triggers are working fine, so I assume there is some issue with the setup of your project or its trigger.

Your trigger is based on connecting a Cloud Source Repository to your GitHub repo. This functionality is documented [here](https://cloud.google.com/source-repositories/docs/connecting-hosted-repositories). Can you please view your [Cloud Source Repository](https://console.cloud.google.com/code/develop/repo) and make sure that it is set up to sync from GitHub the way you expected? If your trigger isn't firing when your code changes, the most likely disconnect is between GitHub and your Cloud Source Repository.

In order for us to debug, we'll need to know what project you are using. Please e-mail us privately at gcr-contact@google.com with your project ID to enable us to debug. If you have more than one trigger set up, please provide additional details to help us identify the trigger in question. Make sure to include a reference to this GitHub issue so that we can tie your bug reports together.

Please note that Build Triggers are [currently a Beta feature](https://cloud.google.com/container-builder/docs/concepts/creating-build-triggers) which is not subject to an SLA.

**Comment by ofpiyush** [comment]
@bendory It happens intermittently, not on every request.

GitHub tells me it successfully delivered all payloads. 

I will pay attention to the response and send an email with request and response of the webhook the next time I see it.

Is this the right place to ask for that "Sync Now" button to force a resync on my Cloud Source Repository?

**Comment by bendory** [comment]
> Is this the right place to ask for that "Sync Now" button to force a resync on my Cloud Source Repository?

@ofpiyush, no this forum is specifically for Google Cloud Container Builder; "Sync Now" would be a feature for Cloud Source Repository.

**Comment by ofpiyush** [comment]
I'll mail you guys with the URL, request and response of the webhook then. Thank you for helping me out! 💯
