### ISSUE TITLE
[BUG] Go builder needs to be upgraded properly in support of go1.16

### ISSUE THREAD

**Issue by bendory** [GoogleCloudPlatform/cloud-builders#753]
With the default `golang` image upgrade from `1.15.8` to `1.16`, our builds broke with messages like "cannot find main module". The [release notes](https://golang.org/doc/go1.16#go-command) state that `GO111MODULE` now defaults to `on` and that the previous behavior is available by setting it to `auto`.

#752 provides a temporary work-around so that our builds succeed.

The real fix will be to properly understand go modules and clean up the go builder examples to work correctly with modules and 1.16.

**Comment by tbpg** [comment]
The issue is that the [examples](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/go/examples) don't all include a `go.mod`.

The Go 1.16 default of `GO111MODULE=on` essentially requires that you have a `go.mod`.

A few options I see:
1. Add a `go.mod` to every example.
    * I saw some examples change `GOPATH` -- those would need to be updated.
2. Specify `GO111MODULE` values for each example, depending on if it has a `go.mod` or not.
3. The builder generates a `go.mod` if it doesn't find one (I don't think this would be ideal).

**Comment by bendory** [comment]
Thank you @tbpg, that was the "push" I needed to figure this out.
