### ISSUE TITLE
Wrong default log directory

### ISSUE THREAD

**Issue by Draiken** [GoogleCloudPlatform/cloud-builders#81]
I am using a service account to perform builds. The command used is pretty standard:
```
gcloud container builds submit  --substitutions "_TAG=$TAG" --config cloudbuild.yaml .
```
The build was created but I had errors when the log was being read:
```
Creating temporary tarball archive of 663 file(s) totalling 4.3 MiB before compression.
Uploading tarball of [.] to [gs://xxxx_cloudbuild/source/xxx.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/xxx/builds/xxx].
Logs are available at [https://console.cloud.google.com/gcr/builds/xxx?project=xxx].
ERROR: (gcloud.container.builds.submit) HTTPError 403: <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Caller does not have storage.objects.get access to object xxx.cloudbuild-logs.googleusercontent.com/log-xxx.txt.</Details></Error>
```
I tried adding extra permissions to the SA but it didn't work.
Finally after some time I decided to manually add the log dir option
```
--gcr-log-dir "gs://<my_project_id>_cloudbuild/logs"
```
And finally the build worked.

From the help text:
```
--gcs-log-dir=GCS_LOG_DIR
        Directory in Google Cloud Storage to hold build logs. If the bucket
        does not exist, it will be created. If not set, gs://<project
        id>_cloudbuild/logs is used.
```
Apparently this is not correct.

My gcloud env:
```
Installed Components:
  core: [2017.06.09]
  pubsub-emulator: [2017.03.24]
  gcloud: []
  beta: [2017.03.24]
  gsutil: [4.26]
  bq: [2.0.24]
  alpha: [2017.03.24]
```

**Comment by ImJasonH** [comment]
We recently changed the default for GCS log buckets, and seemingly failed to update the documentation for the flag's default.

If you don't pass `--gcs-log-dir`, a bucket named like `[project-number].cloudbuild-logs.googleusercontent.com` will be used, which is owned by another project with higher quota limits (which is why we moved to this default). Because the default bucket is owned by another project, you won't be able to augment its ACLs.

You've found the correct solution, which is to specify a `--gcs-log-dir` which is owned by your project, which the service account has access to. I'll update our documentation to reflect the actual behavior. Sorry for any confusion.
