### ISSUE TITLE
Golang. 1.17 Cloud Builder Image

### ISSUE THREAD

**Issue by hthuwal** [GoogleCloudPlatform/cloud-builders#814]
I see that a PR (#812) was merged 6 days ago for creating Golang 1.17 Cloud Builder Image. However, I don't see any image yet in the [GCR repository](https://console.cloud.google.com/gcr/images/cloud-builders/GLOBAL/go) for 1.17. 

I wanted to know an estimate on when the cloud builder image for Golang 1.17 would be available on the GCR.

PS: I asked on the google group and they redirected me here.

**Comment by bendory** [comment]
To report an issue with the hosted Google Cloud Build service, please report it to your Google Cloud Support team. This  repository is solely for issues with the Open Source builders; your question is related to Google's hosted repository.

That said, this issue is expected to materialize later today.
